services:
  postgres:
    container_name: 'postgres14'
    image: 'postgres:14.12'
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'admin'
      POSTGRES_DB: 'test'
    ports:
      - 5432:5432
